In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('/Users/vladkornilov/Desktop/вшэ/Python_Module_1/hw_3_python/Electronic_sales_Sep2023-Sep2024.csv')
df.head(3)

,Customer ID,Age,Gender,Loyalty Member,Product Type,SKU,Rating,Order Status,Payment Method,Total Price,Unit Price,Quantity,Purchase Date,Shipping Type,Add-ons Purchased,Add-on Total
0,1000,53,Male,No,Smartphone,SKU1004,2,Cancelled,Credit Card,5538.33,791.19,7,2024-03-20,Standard,"Accessory,Accessory,Accessory",40.21
1,1000,53,Male,No,Tablet,SKU1002,3,Completed,Paypal,741.09,247.03,3,2024-04-20,Overnight,Impulse Item,26.09
2,1002,41,Male,No,Laptop,SKU1005,3,Completed,Credit Card,1855.84,463.96,4,2023-10-17,Express,NaN,0.00

In [36]:
df2 = df[['Customer ID', 'Payment Method', 'Order Status', 'Total Price', 'Add-on Total']]
df2.head()

   Customer ID Payment Method Order Status  Total Price  Add-on Total
0         1000    Credit Card    Cancelled      5538.33         40.21
1         1000         Paypal    Completed       741.09         26.09
2         1002    Credit Card    Completed      1855.84          0.00
3         1002           Cash    Completed      3164.76         60.16
4         1003           Cash    Completed        41.50         35.56

In [38]:
df2["Order Status"].value_counts()

Order Status
Completed    13432
Cancelled     6568
Name: count, dtype: int64

In [40]:
completed_df2 = df2[df2['Order Status'] == 'Completed']
completed_df2.head()

   Customer ID Payment Method Order Status  Total Price  Add-on Total
1         1000         Paypal    Completed       741.09         26.09
2         1002    Credit Card    Completed      1855.84          0.00
3         1002           Cash    Completed      3164.76         60.16
4         1003           Cash    Completed        41.50         35.56
5         1004    Credit Card    Completed        83.00         65.78

In [41]:
total_spent = completed_df2.groupby('Customer ID')['Total Price'].sum()
total_spent

Customer ID
1000       741.09
1002      5020.60
1003        41.50
1004        83.00
1005     11779.11
           ...
19990     9117.44
19991    12368.06
19995     5394.56
19996    12063.02
19998      674.32
Name: Total Price, Length: 9466, dtype: float64

In [42]:
addons_spent = completed_df2.groupby('Customer ID')['Add-on Total'].sum()
addons_spent

Customer ID
1000      26.09
1002      60.16
1003      35.56
1004      65.78
1005      75.33
          ...
19990    113.56
19991      0.00
19995      0.00
19996    198.98
19998      0.00
Name: Add-on Total, Length: 9466, dtype: float64

In [44]:
orders_count = completed_df2.groupby('Customer ID')['Order Status'].count()
orders_count

Customer ID
1000     1
1002     2
1003     1
1004     1
1005     2
        ..
19990    1
19991    2
19995    1
19996    3
19998    1
Name: Order Status, Length: 9466, dtype: int64

In [47]:
preferred_payment = completed_df2.groupby(['Customer ID', 'Payment Method']).size()
preferred_payment

Customer ID  Payment Method
1000         Paypal            1
1002         Cash              1
             Credit Card       1
1003         Cash              1
1004         Credit Card       1
                              ..
19991        PayPal            1
19995        Credit Card       1
19996        Bank Transfer     2
             Credit Card       1
19998        Bank Transfer     1
Length: 12103, dtype: int64

In [50]:
preferred_payment = preferred_payment.reset_index()
preferred_payment

       index  Customer ID Payment Method  count
0          0         1000         Paypal      1
1          1         1002           Cash      1
2          2         1002    Credit Card      1
3          3         1003           Cash      1
4          4         1004    Credit Card      1
...      ...          ...            ...    ...
12098  12098        19991         PayPal      1
12099  12099        19995    Credit Card      1
12100  12100        19996  Bank Transfer      2
12101  12101        19996    Credit Card      1
12102  12102        19998  Bank Transfer      1

[12103 rows x 4 columns]

In [51]:
preferred_payment = preferred_payment.rename(columns={0: 'count'})
preferred_payment

       index  Customer ID Payment Method  count
0          0         1000         Paypal      1
1          1         1002           Cash      1
2          2         1002    Credit Card      1
3          3         1003           Cash      1
4          4         1004    Credit Card      1
...      ...          ...            ...    ...
12098  12098        19991         PayPal      1
12099  12099        19995    Credit Card      1
12100  12100        19996  Bank Transfer      2
12101  12101        19996    Credit Card      1
12102  12102        19998  Bank Transfer      1

[12103 rows x 4 columns]

In [53]:
preferred_payment = preferred_payment.sort_values(
    ['Customer ID', 'count', 'Payment Method'],
    ascending = [True, False, True]
)
preferred_payment

       index  Customer ID Payment Method  count
0          0         1000         Paypal      1
1          1         1002           Cash      1
2          2         1002    Credit Card      1
3          3         1003           Cash      1
4          4         1004    Credit Card      1
...      ...          ...            ...    ...
12098  12098        19991         PayPal      1
12099  12099        19995    Credit Card      1
12100  12100        19996  Bank Transfer      2
12101  12101        19996    Credit Card      1
12102  12102        19998  Bank Transfer      1

[12103 rows x 4 columns]

In [56]:
preferred_payment = preferred_payment.drop_duplicates('Customer ID')
preferred_payment

       index  Customer ID Payment Method  count
0          0         1000         Paypal      1
1          1         1002           Cash      1
3          3         1003           Cash      1
4          4         1004    Credit Card      1
5          5         1005     Debit Card      1
...      ...          ...            ...    ...
12096  12096        19990         PayPal      1
12097  12097        19991    Credit Card      1
12099  12099        19995    Credit Card      1
12100  12100        19996  Bank Transfer      2
12102  12102        19998  Bank Transfer      1

[9466 rows x 4 columns]

In [58]:
preferred_payment = preferred_payment[
    ["Customer ID", "Payment Method"]
]
preferred_payment

       Customer ID Payment Method
0             1000         Paypal
1             1002           Cash
3             1003           Cash
4             1004    Credit Card
5             1005     Debit Card
...            ...            ...
12096        19990         PayPal
12097        19991    Credit Card
12099        19995    Credit Card
12100        19996  Bank Transfer
12102        19998  Bank Transfer

[9466 rows x 2 columns]

In [59]:
preferred_payment = preferred_payment.rename(columns={'Payment Method': 'preferred_payment'})
preferred_payment

       Customer ID preferred_payment
0             1000            Paypal
1             1002              Cash
3             1003              Cash
4             1004       Credit Card
5             1005        Debit Card
...            ...               ...
12096        19990            PayPal
12097        19991       Credit Card
12099        19995       Credit Card
12100        19996     Bank Transfer
12102        19998     Bank Transfer

[9466 rows x 2 columns]

In [63]:
total_spent = total_spent.reset_index()
total_spent = total_spent.rename(columns={'Total Price': 'total_spent'})
total_spent

      index  Customer ID  total_spent
0         0         1000       741.09
1         1         1002      5020.60
2         2         1003        41.50
3         3         1004        83.00
4         4         1005     11779.11
...     ...          ...          ...
9461   9461        19990      9117.44
9462   9462        19991     12368.06
9463   9463        19995      5394.56
9464   9464        19996     12063.02
9465   9465        19998       674.32

[9466 rows x 3 columns]

In [65]:
addons_spent = addons_spent.reset_index()

In [67]:
addons_spent = addons_spent.rename(columns={'Add-on Total': 'addons_spent'})

In [72]:
orders_count = orders_count.reset_index()

In [75]:
orders_count = orders_count.rename(columns={'Order Status': 'orders_count'})

In [77]:
final_df = preferred_payment.merge(
    total_spent, on = 'Customer ID'
)

In [79]:
final_df = final_df.merge(
    addons_spent, on = 'Customer ID'
)

In [81]:
final_df = final_df.merge(
    orders_count, on = 'Customer ID'
)

In [83]:
final_df = final_df[['Customer ID', 'preferred_payment', 'total_spent', 'addons_spent', 'orders_count']]

In [85]:
final_df = final_df.sort_values('total_spent', ascending = False)

In [89]:
result = final_df.head(10)
result

      Customer ID preferred_payment  total_spent  addons_spent  orders_count
5048        11476            PayPal     29937.93        198.42             4
7095        15399            PayPal     29084.88        305.39             3
6177        13635       Credit Card     28093.28        388.11             4
7584        16357     Bank Transfer     27486.01        352.75             6
4960        11332            PayPal     26725.65        240.24             4
5489        12294     Bank Transfer     26575.02        477.68             4
839          2556        Debit Card     26098.40        230.66             6
6124        13534     Bank Transfer     25893.60        367.61             5
6589        14436       Credit Card     24912.42        102.31             4
6266        13797     Bank Transfer     24870.42         78.83             3